name: Archive/Unarchive Repo

on:
  issues:
    types: [opened, edited]

    # expected issue body input should be structured as follows:
  #     {
  #         "rep01": {
  #             "repository": "rep01",
  #             "organisation": "org01"
  #         },
  #         "rep02": {
  #             "repository": "rep02",
  #             "organisation": "org02"
  #         }
  #     }
 

jobs:
  issue_flow:
    runs-on: ubuntu-latest
    strategy:  
            matrix:
                repository: ${{ fromJson(github.event.issue.body).*.repository }}  # rep01, repo02
            max-parallel: 1
    owner: '${{ fromJSON(github.event.issue.body)[matrix.repository].organisation }}

    steps:
        - name: echo
          run: |
            echo "${{repository}}"
            echo "${{owner}}"