name: Archive/Unarchive Repo

on:
    issue_comment:
        types: [created]
jobs:
  issue_flow:
    runs-on: ubuntu-latest
    strategy:  
      matrix:
        repository: ${{ fromJson(github.event.issue.body).*.repository }}  # rep01, repo02
      max-parallel: 1
       
    steps:
      - name: Extract Repository and Owner
        id: extract_repo_owner
        run: |
          # Extract repository and organization names from the issue body
          repository=${{ matrix.repository }}
          Owner: ${{ fromJSON(github.event.issue.body)[matrix.repository].organisation }}
          #owner=${{ env.Owner }}
          echo "Repo = $repository"
          echo "Owner = $Owner"
    

          # Echo repository and owner names as output
            #echo "repo-name=$repository" >> $GITHUB_OUTPUT
            #echo "owner-name=$owner" >> $GITHUB_OUTPUT

    
