name: Archive/Unarchive Repo

on:
  issues:
    types: [opened, edited]
jobs:
  issue_flow:
    runs-on: ubuntu-latest
    strategy:  
      matrix:
        repository: ${{ fromJson(github.event.issue.body).*.repository }}  # rep01, repo02
        owner: ${{ fromJSON(github.event.issue.body).*.organisation }}
      max-parallel: 1

      
    outputs:  
      Repo-name: ${{ steps.extract_repo_owner.outputs.repo_name }}
      Owner-name: ${{ steps.extract_repo_owner.outputs.owner-name }}  
    steps:
      - name: Extract Repository and Owner
        id: extract_repo_owner
        run: |
          # Extract repository and organization names from the issue body
          repository=${{ fromJSON(github.event.issue.body)[matrix.repository].repository }}
          owner=${{ fromJSON(github.event.issue.body)[matrix.repository].organisation }}
    
    

          # Echo repository and owner names as output
            echo "repo-name=$repository" >> $GITHUB_OUTPUT
            echo "owner-name=$owner" >> $GITHUB_OUTPUT
          
      
      - name: Access it
        run: |
            echo "Repo Name is ${{ steps.extract_repo_owner.outputs.repo-name }}"
            echo "Owner name is ${{ steps.extract_repo_owner.outputs.owner-name }}"

    
