name: Unlock Repository

on:
  workflow_dispatch:
    inputs:
      repository:
        description: 'Repository name with owner (e.g., owner/repo)'
        required: true

jobs:
  unlock-repo:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Run Python script to unlock repository
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        REPO_NAME: ${{ github.event.inputs.repository }}
      run: |
        python unlock_repository.py $REPO_NAME
