name: Unlock Repository

on:
  workflow_dispatch:
    inputs:
      repository:
        description: 'Repository name with owner (e.g., owner/repo)'
        required: true

jobs:
  unlock-repo:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Unlock repository
      run: |
        TOKEN=$GITHUB_TOKEN
        REPO=$INPUT_REPOSITORY
        curl -X DELETE -H "Authorization: token $TOKEN" "https://api.github.com/repos/$REPO/branches/main/protection"
