name: Unlock Repository

on:
  workflow_dispatch:
    inputs:
      repository:
        description: 'Repository name with owner (e.g., owner/repo)'
        required: true

jobs:
  unlock-repo:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Unlock repository
      env:
        GITHUB_TOKEN: ${{ secrets.WORK_GITHUB_TOKEN }}
        REPO_NAME: ${{ github.event.inputs.repository }}
      run: |
        # Construct the API endpoint URL
        API_URL="https://api.github.com/repos/Git-practice-9922/git-actions/branches/master/protection"
        
        # Send DELETE request to remove branch protection using curl
        curl -X PUT -H "Authorization: token $WORK_GITHUB_TOKEN" "$API_URL" \
        -d '{"required_status_checks": null,
         "enforce_admins":false,"required_pull_request_reviews":null,"dismiss_stale_reviews":false,
         "require_code_owner_reviews":false,"required_approving_review_count":null,"require_last_push_approval":false,"restrictions":null,
         "required_linear_history":false,"allow_force_pushes":false,"allow_deletions":false,"block_creations":false,"required_conversation_resolution":false,"lock_branch":true,"allow_fork_syncing":false}'
