name: List Repositories and IDs

on:
  workflow_dispatch:

jobs:
  list-repos:
    runs-on: ubuntu-latest

    steps:
    - name: Install jq
      run: sudo apt-get update && sudo apt-get install -y jq 

    - name: List Repositories 
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # Construct the API endpoint URL to list repositories
        API_URL="https://api.github.com/users/Git-practice-9922/repos"
        
        # Send GET request to list repositories using curl
        response=$(curl -H "Authorization: token $GITHUB_TOKEN" "$API_URL")
        
        # Extract repository names and IDs from the JSON response
        repos=$(echo "$response" | jq -r '.[] | "\(.full_name) \(.id)"')
        
        # Print repository names and IDs
        echo "Repository Name | Repository ID"
        echo "$repos"